[package]
name = "hatel"
version = "0.1.0"
authors = ["Alan Morgan <alanxoc3@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.3"
midir = "0.7.0"
clap = { version = "3.1.0", features = ["derive"] }
